language: node_js
node_js:
  - "4.0"
before_install:
  npm install -g npm@'>=3.9.6'
before_script:
  - npm install -g gulp
  - gulp --production
after_success:
  - surge --project ./public --domain sara.hilloco.se
branches:
  only:
    - production
